# docker-compose-working.yml
# Configuration using dev.scram2k.com domain (confirmed working in infrastructure)
version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-entersys-backend
    restart: unless-stopped
    
    # Cargar variables de entorno desde el archivo .env
    env_file:
      - .env
      
    # Conectar a la red externa de Traefik
    networks:
      - traefik_network
      
    # Etiquetas para la auto-configuración de Traefik usando dev.scram2k.com
    labels:
      - "traefik.enable=true"
      # Regla: usar dev.scram2k.com con path /backend/
      - "traefik.http.routers.entersys-backend-dev.rule=Host(`dev.scram2k.com`) && PathPrefix(`/backend/`)"
      # Punto de entrada: usar el puerto 443 (HTTPS)
      - "traefik.http.routers.entersys-backend-dev.entrypoints=websecure"
      # Certificado SSL: Usar Let's Encrypt para obtenerlo
      - "traefik.http.routers.entersys-backend-dev.tls.certresolver=letsencrypt"
      # Servicio: Indicar a Traefik que el puerto interno de la app es 8000
      - "traefik.http.services.entersys-backend-dev.loadbalancer.server.port=8000"
      # Middleware para strip el prefix /backend
      - "traefik.http.routers.entersys-backend-dev.middlewares=entersys-backend-stripprefix"
      - "traefik.http.middlewares.entersys-backend-stripprefix.stripprefix.prefixes=/backend"

networks:
  # Definir que usaremos la red 'traefik' que ya existe en el host
  traefik_network:
    name: traefik
    external: true