"""Add support module tables

Revision ID: 87310d6ccbda
Revises: a1b2c3d4e5f6
Create Date: 2025-12-04 01:28:06.466561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87310d6ccbda'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_chat_nodes',
    sa.Column('node_key', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('external_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('node_key')
    )
    op.create_index(op.f('ix_sys_chat_nodes_node_key'), 'sys_chat_nodes', ['node_key'], unique=False)
    op.create_table('sys_support_faq',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_support_faq_id'), 'sys_support_faq', ['id'], unique=False)
    op.create_table('sys_chat_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_node_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('next_node_key', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['next_node_key'], ['sys_chat_nodes.node_key'], ),
    sa.ForeignKeyConstraint(['parent_node_key'], ['sys_chat_nodes.node_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_chat_options_id'), 'sys_chat_options', ['id'], unique=False)
    op.add_column('admin_users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('reset_token_expires', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_admin_users_reset_token'), 'admin_users', ['reset_token'], unique=False)
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_users_reset_token'), table_name='admin_users')
    op.drop_column('admin_users', 'reset_token_expires')
    op.drop_column('admin_users', 'reset_token')
    op.drop_column('admin_users', 'full_name')
    op.drop_index(op.f('ix_sys_chat_options_id'), table_name='sys_chat_options')
    op.drop_table('sys_chat_options')
    op.drop_index(op.f('ix_sys_support_faq_id'), table_name='sys_support_faq')
    op.drop_table('sys_support_faq')
    op.drop_index(op.f('ix_sys_chat_nodes_node_key'), table_name='sys_chat_nodes')
    op.drop_table('sys_chat_nodes')
    # ### end Alembic commands ###
